### ISSUE TITLE
Incorrect discord link

### ISSUE THREAD

**Issue by HarshPatel5940** [vinay-04/vinay-04#1]
change 
`[![Discord](https://img.shields.io/badge/Discord-%237289DA.svg?logo=discord&logoColor=white)](https://discord.gg/https://discord.com/users/709417842256248943)`
to
`[![Discord](https://img.shields.io/badge/Discord-%237289DA.svg?logo=discord&logoColor=white)](https://discord.com/users/709417842256248943)`

**Comment by vinay-04** [comment]
Resolved
